### ISSUE TITLE
Hmm

### ISSUE THREAD

**Issue by cal97g** [mardix/webportfolio#1]
Looks handy, does it work?

**Comment by mardix** [comment]
:) Yes it works.

Currently powering http://thelastfight.com 

At this time WebPortfolio is in Alpha. Going thru all the normal use cases for using it on a website, and fixing bugs. 

But upon installing it, it should work fine. 

Also, I'm in the process of writing the doc. 

I'll announce it's first release when it's at 0.1.0. For now it's 0.0.23 

Thanks for checking it out
